### ISSUE TITLE
Anyway to get details of parsed object?

### ISSUE THREAD

**Issue by jplock** [jknack/semver.java#1]
After doing:

```
Semver version = Semver.create("1.2.3");
```

Is there anyway to expose the Version.getMajor(), Version.getMinor(), etc. methods off of the Semver itself?  I want to be able to do version.getMajor() and have it return "1"

Thanks!

**Comment by loganvolkers** [comment]
Try this library, it seems to be more full featured: https://github.com/vdurmont/semver4j

I think it has all the things you're asking for:

- [x] `getMajor()`
- [x] `getMinor()`
- [x] `getPatch()`
- [x] `getSuffixTokens()`
- [x] `getBuild()`
- [x] `isStable()`

**Comment by jplock** [comment]
wow, thanks for the response @loganvolkers.  I don't even remember what I was doing 5 years ago when I asked this.
